[mongodb]
url="mico-project.ho2lj.mongodb.net"
Port="27017"
database="demo-mico-project"
user="dev-mico"
password="45jqkLRsCnvkf5EZ"

[mailjet]
ApiKey="f87457af01a6c511457b0d34f39d365b"
SecretKey="cb5327d3199519e44bc265d8b93ef5d1"
AdminMail="info@mico.earth"

[bucket]
name="mico_project"
profile=""
assets=""
portofolio=""

[swagger]
Host="demo.mico.earth"
Protocol="https"
BasePath="/v1"

[frontend]
url="demo.mico.earth"
protocol="https"

[collections]
users="users"
vendor="vendor"
item="item"
address="address"
questions="questions"
house_part="house_part"
house_part_category="house_part_category"
house_part_subcategory="house_part_subcategory"
Items_sku="Items_sku"
chart="chart"
checkout="checkout"
checkout_id="checkout_id"
transaction="transaction"
content="content"
content_tags="content_tags"
content_sub_tags="content_sub_tags"
content_sub_sub_tags="content_sub_sub_tags"
mico_values="mico_values"
bad_item="bad_item"
country="country"
admin="admin"
persona_question="persona_question"
persona_answer="persona_answer"
persona_bucket="persona_bucket"
country_city="country_city"
user_persona_answer="user_persona_answer"
persona="persona"




[stripe]
SecretKey="sk_test_51Jhqh6F8sq9RvyoVSqhBzXqBW0nifMDO8KGmdbv9RVD9CIBWSGtvK1EgQss0uBF7ropRSQWc0aTITKZLNyAdq0A200XsLYpzm4"
PublishableKey="pk_test_51Jhqh6F8sq9RvyoVMjLh2VaIno0Nj113z1AcwRUBtbStrBKkt7fUUEh3q6MDMvQO8plPNKNZF2eZWwvthXxMZGel000631vjRf"
WebhookEndpointSecret="whsec_Hr6KTDAg5ttmZBoq1zRE8N3msJE3NlOc"